export interface ProductModel {
    sku:string,
    productName: string,
    import: number,
    export: number,
    balance: number,
    productCost: number,
    productPrice: number,
    type: string,
    importDate: Date,
    exportDate: Date,
    updateDate: Date,
    roastDate: Date,
    updateUSer: string,
}